package-lock.json, package.json, src/Common/ErrorScreenNotFound.tsx
1. 404 status redirection url updated
Ticket [AB 2466](https://dev.azure.com/DevtronLabs/Devtron/_boards/board/t/OSS%20adoption/Stories/?workitem=2466)
=> feat: updated the error screen not found redirection

package.json, src/Common/Api.ts, src/Common/Constants.ts
This PR contains the fixes for auto logout on 401
Tested manually by removing the local cookie
=> fix: Auto log out on unauthorized fixed

package-lock.json, package.json, src/Common/EmptyState/GenericEmptyState.tsx, src/Common/Types.ts
Added margin top in the generic title
=> fix: for generic title

package-lock.json, package.json
=> version upgrade 0.0.9

package.json, src/Common/Constants.ts, src/Common/EmptyState/GenericEmptyState.tsx, src/Common/Types.ts
Svg Imaga has been handled in the GenericEmptyState function.
=> fix: Svg Image handling

package.json, src/Common/Common.service.ts, src/Common/EmptyState/GenericEmptyState.tsx, src/Common/Helper.tsx, src/Common/ImageTags.tsx, src/Common/Types.ts
added useSearchString function
=> feat: search string function

package-lock.json, package.json
Version update from v0.0.21 to v0.0.22
=> Package.json version change

package-lock.json
version upgrade from v0.0.21 to v0.0.22
=> version change 

package.json, src/Common/Helper.tsx
Feat: Extracted common function for closeOnKeyPressed action
This will go along with the PR: https://github.com/devtron-labs/dashboard/pull/1223
=> feat: closeOnKeyPressed function

package.json
Updated version for import error of the function closeOnEscKeyPressed
=> feat: updated version for custom chart download

package.json, src/Common/Hooks/UseClickOutside/UseClickOutside.tsx, src/Common/Hooks/index.ts
Hook to add effect on outside click
=> feat: add useClickOutside

package.json, src/Common/Types.ts
Add types for CdPipeline and CiPipeline
=> chore: add ci types

package.json, src/Common/DebouncedSearch/DebouncedSearch.tsx, src/Common/DebouncedSearch/Types.ts, src/Common/Dialogs/DeleteDialog.tsx, src/Common/Dialogs/Types.ts, src/Common/Types.ts
Adding type of isLinkedCD in node attr and opening up prop for autoFocus in DebouncedSearch.
=> chore: add type for isLinkedCD in node attr

src/Common/RJSF/templates/ObjectFieldTemplate.tsx, src/Common/RJSF/utils.ts
1. Padding change in label container, for rjsf modal
2. Multi select chip update.
=> chore: rjsf-uat

package.json, src/Common/Helper.tsx
- Add exception logger for sentry
=> feat: add exception logger for sentry along with select picker style fixes

package.json, src/Common/AddCDButton/AddCDButton.tsx, src/Common/AddCDButton/types.ts, src/Common/Types.ts
Adding changes to support tooltip in add cd buttons
=> feat: add cd buttons tippy

package-lock.json, package.json, src/Common/CustomInput/CustomInput.tsx, src/Common/CustomInput/Types.ts
Label Type Fix in custom input
=> fix:  for label type

package.json, src/Common/Api.ts, src/Common/Constants.ts
Deriving requestTimeout from env
=> feat: timeout flags

package.json, src/Common/Api.ts
add empty check for GLOBAL_API_TIMEOUT
=> fix: add empty check for GLOBAL_API_TIMEOUT

package-lock.json, package.json, src/Common/CustomInput/CustomInput.tsx, src/Common/CustomInput/Types.ts
Custom Input Wrapper classname
- [] Bug fix (non-breaking change which fixes an issue)
- [] This change requires a documentation update
=> feat: Custom input v2 lib

package-lock.json, package.json, src/Common/Hooks/useUrlFilters/useUrlFilters.ts, src/Pages/GlobalConfigurations/Authorization/constants.ts, src/Pages/GlobalConfigurations/Authorization/index.ts, src/Pages/GlobalConfigurations/index.ts, src/Pages/index.ts, src/index.ts
- add common constants for user status
=> feat: add common constants for user status

package-lock.json, package.json, src/Common/CustomInput/CustomInput.tsx, src/Common/CustomInput/Types.ts, src/Common/SearchBar/SearchBar.component.tsx, src/Common/SearchBar/types.ts
=> fix: Image digest common uat

src/Common/CustomInput/CustomInput.tsx, src/Common/CustomInput/Types.ts
Custom app data index attribute miss
=> fix: data index attribute

package-lock.json, package.json
=> feat: updated version of digest

package.json, src/Common/Types.ts, src/Pages/GlobalConfigurations/BuildInfra/constants.tsx, src/Pages/GlobalConfigurations/BuildInfra/utils.tsx, src/Shared/Components/BulkSelection/BulkSelectionDropdownItems.tsx, src/Shared/validations.tsx
Adding a validator function to validate required positive integer and move validation texts to a constant.
=> fix: build timeout validation

src/Pages/GlobalConfigurations/BuildInfra/Footer.tsx
Cancel button in build infra form on loading should be disabled.
=> fix: disable infra form

package-lock.json, package.json, src/Common/SearchBar/SearchBar.component.tsx, src/Common/SearchBar/types.ts
- Props opened for search
- onclear issue fix for search
=> fix: search bar clear search fix

package.json, src/Pages/GlobalConfigurations/BuildInfra/utils.tsx, src/Shared/Components/BulkSelection/BulkSelectionDropdownItems.tsx
Adding styles to unit selector dropdown and bulk select dropdown
=> uat: build infra

package-lock.json, package.json, src/Common/AddCDButton/AddCDButton.tsx, src/Common/AppStatus/AppStatus.tsx
=> fix: Vite exploration lib bug

package-lock.json, package.json, src/Common/AddCDButton/AddCDButton.tsx
=> fix: Vite exploration bugs

src/Shared/Components/KeyValueList/KeyValueList.tsx, src/Shared/Components/KeyValueList/types.ts
add itemClassName prop for key value list
=> feat: itemClassName prop for key value list

src/Common/Types.ts, src/Shared/Components/Vulnerabilities/Vulnerabilities.tsx, src/Shared/types.ts
Add types related to WorkflowType and WorkflowTypes itself
=> feat: add workflow type

package-lock.json, package.json, src/Common/AddCDButton/types.ts, src/Common/AddCDButton/utils.tsx, src/Pages/GlobalConfigurations/BuildInfra/BuildInfraFormAction.tsx
send parent pipeline as webhook only for ci parent
=> fix: send parent pipeline as webhook only for ci parent

package-lock.json, package.json, src/Common/TippyCustomized.tsx
Deployment window tippy onclose
=> Fix: Deployment window tippy onclose 

package-lock.json, package.json, src/Common/Helper.tsx, src/Shared/validations.tsx
=> feat: create release and release track

package-lock.json, package.json, src/Common/CodeEditor/CodeEditor.tsx, src/Common/Helper.tsx
Generalize yaml stringify:
Bump yaml version to "2.4.1"
=> feat: Generalize yaml stringify

package-lock.json, package.json, src/index.ts
Add a ConfigMap flag to hide GitOps repo and based on that flag, the GitOps url will be shown.
=> feat: user-defined gitops repo enable variable

package-lock.json, package.json, src/Shared/Components/ReactSelect/utils.tsx
=> fix: styling for react select

package-lock.json, package.json, src/Shared/Components/EditableTextArea/EditableTextArea.tsx, src/Shared/types.ts
=> fix: add trimming in editable text area and make value optional

package-lock.json, package.json, src/Common/Drawer/Drawer.tsx, src/Common/Helper.tsx, src/Common/Modals/VisibleModal.tsx, src/Common/Modals/VisibleModal2.tsx, src/Shared/Components/BulkSelection/BulkSelection.tsx, src/Shared/Components/BulkSelection/types.tsx
- update typing for useAysnc
- prevent body scroll for visible modal, visible2 modal and drawer
=> fix: update typing for useAysnc, prevent body scroll for modals

package-lock.json, package.json, src/index.ts
This PR adds a flag to customEnv for enabling gitops bitbucket-source setup.
=> feat: add bitbucket-source flag

src/Common/GenericDescription/GenericDescription.tsx
=> fix: add truncation in generic description

package-lock.json, package.json, src/Common/Api.ts, src/Common/Common.service.ts, src/Common/ErrorPage.tsx, src/Common/ErrorScreenManager.tsx, src/Common/Types.ts
This PR contains changes to add information related to release like, its source release and some meta info like artifact workflow id into cdmaterial type
=> feat: add artifact release mapping info in cd material type

package-lock.json, package.json, src/Shared/constants.tsx
Add default secret placeholder constant
=> feat: add DEFAULT_SECRET_PLACEHOLDER

package-lock.json, package.json, src/index.ts
=> feat: added resource watcher flag

src/Shared/Providers/ImageSelectionUtility/types.ts
=> feat: cicd history

package-lock.json, package.json, src/Common/Dialogs/DeleteDialog.tsx, src/Shared/Services/cluster.service.ts
=> feat: add sorting for the cluster list

package-lock.json, package.json, src/Shared/Helpers.tsx, src/Shared/types.ts, src/index.ts
Remove unused flags from customEnv and add new enum key for authMode
=> feat: add ssh and password type

package-lock.json, package.json, src/Common/Constants.ts
Update Documentation Version from v0.6 to v0.7
=> feat: update documentation version

package-lock.json, package.json
=> fix: versioning up to 0.1.3

package-lock.json, package.json, src/Shared/Components/DatePicker/DateTimePicker.tsx, src/Shared/Components/DatePicker/datePicker.scss, src/Shared/Components/DatePicker/types.ts
- fix: styling and disabled support for date time picker
=> fix: styling and disabled support for date time picker

.eslintrc.cjs, package-lock.json, package.json
This PR updates react select version to 5.8.0 as peer dependency
=> feat: update react select version to 5.8.0

src/Common/Policy.Types.ts, src/Shared/Components/Plugin/service.tsx, src/Shared/Components/Plugin/types.ts, src/Shared/Components/Plugin/utils.tsx
Add props to configure showError for mandatory plugins
=> feat: add prop to configure showError for mandatory plugins

src/Shared/Components/Plugin/PluginCard.tsx, src/Shared/Components/Plugin/PluginListContainer.tsx
Add stopPropagation for learn more link in plugin list
=> fix: add stopPropagation for learn more link in plugin list

package-lock.json, package.json, src/Shared/Components/Plugin/PluginListContainer.tsx, src/Shared/Components/Plugin/service.tsx, src/Shared/Components/Plugin/types.ts
This PR includes fix for sorting plugin list
=> fix: sorting for parent plugin list

src/Shared/Components/CICDHistory/DeploymentHistoryDiff/DeploymentHistoryDiffView.tsx, src/Shared/Components/CICDHistory/types.tsx
DeploymentHistoryDiffView - add overwrite className support
=> chore: DeploymentHistoryDiffView - add overwrite className support

src/Shared/Components/FilterChips/FilterChips.component.tsx, src/Shared/Components/FilterChips/types.ts, src/Shared/Services/types.ts, src/Shared/types.ts
=> feat: add support for hiding the remove button in filter chips & rename policy sub kind to policy kind

src/Shared/Hooks/index.ts, src/Shared/Hooks/useGetResourceKindsOptions/index.ts, src/Shared/Hooks/useGetResourceKindsOptions/service.ts, src/Shared/Hooks/useGetResourceKindsOptions/types.ts, src/Shared/Hooks/useGetResourceKindsOptions/useGetResourceKindsOptions.tsx, src/Shared/Hooks/useGetResourceKindsOptions/utils.ts
- feat: add useGetResourceKindsOptions for resource list
=> feat: add useGetResourceKindsOptions for resource list

src/Common/CodeEditor/CodeEditor.tsx, src/Common/CodeEditor/types.ts, src/Shared/Services/common.service.ts, src/Shared/Services/types.ts
=> fix: add suffix support to resource and policy url getters

package-lock.json, package.json, src/Shared/Components/CICDHistory/LogStageAccordion.tsx, src/Shared/Components/CICDHistory/LogsRenderer.tsx, src/Shared/Helpers.tsx
- Add log stage status as failure in case event are not progressing and end stage is not there.
- Show time as < 1s instead of 0s
=> fix: log stage time status

package-lock.json, package.json, src/Common/Constants.ts, src/Shared/Components/CICDHistory/Artifacts.tsx, src/Shared/Components/CICDHistory/TriggerOutput.tsx, src/Shared/Components/CICDHistory/service.tsx, src/Shared/Components/CICDHistory/types.tsx, src/Shared/Helpers.tsx, src/Shared/Hooks/UseDownload/UseDownload.tsx, src/Shared/Hooks/UseDownload/utils.tsx
use useDownload Hook to download files/folders globally
=> feat: use useDownload globally

src/Common/ChartVersionAndTypeSelector.tsx
=> chore: reuse util css

package-lock.json, package.json, src/Common/CodeEditor/CodeEditor.tsx, src/Common/CodeEditor/types.ts
This reverts commit 5599bd7924215f94c431808ae6300b6e925693b9.
=> Revert "feat: add support for width in CodeEditor"

package-lock.json, package.json, src/index.ts
=> feat: image promotion gc

package-lock.json, package.json, src/Common/SortableTableHeaderCell/SortableTableHeaderCell.tsx, src/Shared/constants.tsx
=> feat: lock config v2

package-lock.json, package.json, src/Common/CodeEditor/CodeEditor.tsx, src/Common/CodeEditor/types.ts, src/Common/Constants.ts, src/Common/RJSF/constants.ts, src/Common/RJSF/index.ts, src/Pages/GlobalConfigurations/DeploymentCharts/basicViewSchema.json, src/Pages/GlobalConfigurations/DeploymentCharts/fallbackJobsNCronJobGuiSchema.json, src/Pages/GlobalConfigurations/DeploymentCharts/index.ts, src/Pages/GlobalConfigurations/DeploymentCharts/types.ts, src/Pages/GlobalConfigurations/DeploymentCharts/utils.ts, src/Pages/GlobalConfigurations/index.ts, src/Shared/Helpers.tsx, src/Shared/validations.tsx
=> feat: editable gui schema on deployment charts

package-lock.json, package.json, src/Shared/Components/SelectPicker/SelectPicker.component.tsx, src/Shared/Components/SelectPicker/type.ts, src/Shared/Components/SelectPicker/utils.ts, src/Shared/Hooks/UseDownload/UseDownload.tsx
add support to align menu to right in select picker
=> feat: add support to align menu to right in select picker

package-lock.json, package.json, src/Common/Types.ts, src/Pages/GlobalConfigurations/Authorization/index.ts, src/Pages/GlobalConfigurations/Authorization/service.ts, src/Pages/GlobalConfigurations/Authorization/types.ts, src/Shared/Components/SelectPickerCustom/index.ts
feat: add support for any & specific approval type in cd pipeline
=> feat: add support for any & specific approval type in cd pipeline

package-lock.json, package.json, src/Common/Common.service.ts, src/Common/Types.ts, src/Shared/Components/CICDHistory/Artifacts.tsx, src/Shared/Components/CICDHistory/History.components.tsx
adding approval config inside user approval metadata if not present inside it, from parent
=> fix: approve material

package-lock.json, package.json, src/Shared/Components/SelectPickerCustom/utils.ts
=> fix: color for single value for border less select

src/Common/Pagination/Pagination.tsx, src/Common/Pagination/pagination.scss, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.scss, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiffMain.tsx, src/Shared/constants.tsx
=> fix: config diff compare height

src/Shared/Components/SelectPicker/SelectPicker.component.tsx, src/Shared/Components/SelectPicker/common.tsx, src/Shared/Components/SelectPicker/type.ts
fix: closure issue with renderMenuListFooter
=> fix: closure issue with renderMenuListFooter

package-lock.json, package.json, src/Shared/Components/SelectPicker/type.ts
=> fix: type issue for select picker module augmentation

package-lock.json, package.json, src/Shared/Components/SelectPicker/FilterSelectPicker.tsx, src/Shared/Components/SelectPicker/SelectPicker.component.tsx, src/Shared/Components/SelectPicker/common.tsx, src/Shared/Components/SelectPicker/type.ts
=> fix: typing for select picker and menu list renderer

package-lock.json, package.json, src/Shared/Components/CICDHistory/Artifacts.tsx, src/Shared/Components/MaterialHistory/MaterialHistory.component.tsx
1. Artifact Error check Added
2. Webhook Date separator removed from Build trigger list
=> fix: webhook date separator

package-lock.json, package.json, src/Shared/Components/CICDHistory/Artifacts.tsx, src/Shared/Components/MaterialHistory/MaterialHistory.component.tsx
webhook date separator removed
=> fix: webhook date separator removed

package-lock.json, package.json, src/Shared/Components/Plugin/PluginCard.tsx
=> fix: create plugin QA issues

package-lock.json, package.json, src/Common/CodeEditor/CodeEditor.tsx, src/Common/CodeEditor/types.ts, src/Shared/Components/CICDHistory/DeploymentHistoryDiff/DeploymentHistoryDetailedView.tsx, src/Shared/Components/CICDHistory/DeploymentHistoryDiff/DeploymentHistoryDiffView.tsx, src/Shared/Components/CICDHistory/DeploymentHistoryDiff/styles.scss, src/Shared/Components/Collapse/Collapse.tsx, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.scss, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiffMain.tsx, src/Shared/constants.tsx
=> feat: disable search and use dynamic height in config diff

.github/CODEOWNERS, package-lock.json, package.json, src/Common/Tooltip/Tooltip.tsx, src/Shared/Components/SelectPicker/SelectPicker.component.tsx, src/Shared/Components/SelectPicker/type.ts
add option list error in filter select
hide footer on filter select error
=> feat: hide footer on filter select error

package-lock.json, package.json, src/Common/Tooltip/Tooltip.tsx, src/Shared/Components/Button/Button.component.tsx, src/Shared/Components/Button/button.scss, src/Shared/Components/Button/types.ts
feat: add support for link in button
=> feat: add support for link in button

package-lock.json, package.json, src/Common/ClipboardButton/ClipboardButton.tsx
=> fix: dont use internal trigger if controlled from outside

package-lock.json, package.json, src/Common/ClipboardButton/ClipboardButton.tsx
=> chore: main sync

package-lock.json, package.json, src/Shared/Components/CICDHistory/DeploymentHistoryDiff/DeploymentHistoryConfigList.component.tsx
=> chore: deployment history css fix

package-lock.json, package.json
=> chore: main sync for release candidate 18

package-lock.json, package.json, src/Shared/Components/CICDHistory/Artifacts.tsx
fix: show artifacts when blob storage is disabled and in jobs 
Fixes https://github.com/devtron-labs/devtron/issues/5605
=> fix: show artifacts when blob storage is disabled

package-lock.json, package.json, src/Common/Drawer/Drawer.tsx, src/Shared/Components/CICDHistory/StatusFilterButtonComponent.scss, src/Shared/Components/CICDHistory/StatusFilterButtonComponent.tsx, src/Shared/Components/TabGroup/TabGroup.component.tsx, src/Shared/Components/TabGroup/TabGroup.helpers.tsx, src/Shared/Components/TabGroup/TabGroup.scss, src/Shared/Components/TabGroup/TabGroup.types.ts, src/Shared/Components/TabGroup/TabGroup.utils.ts
feat: StatusFilterButton - UI update
feat: Drawer - onClose prop support
=> feat: TabGroup - add xl size variant, add description support

package-lock.json, package.json, src/Shared/Components/Header/HeaderWithCreateButton/HeaderWithCreateButon.tsx
fix: redirection on create app modal close
=> fix: redirection on create app modal close

.github/semantic.yml, package-lock.json, package.json, src/Shared/Components/CICDHistory/Artifacts.tsx
=> chore: sync main dt19

package-lock.json, package.json, src/Assets/Icon/ic-close.svg, src/Shared/Services/ToastManager/constants.tsx, src/Shared/Services/ToastManager/toastManager.scss
=> fix: close icon override

src/Common/RJSF/utils.tsx, src/Shared/Components/TabGroup/TabGroup.component.tsx
=> fix: TabGroup: onClick preventDefault when tab is in active state

package-lock.json, package.json, src/Shared/Components/TabGroup/TabGroup.component.tsx
fix: TabGroup onClick null check
=> fix: TabGroup onClick null check

package-lock.json, package.json, src/Shared/Components/ArtifactInfoModal/ArtifactInfoModal.component.tsx, src/Shared/Components/CICDHistory/Artifacts.tsx, src/Shared/Components/CICDHistory/TriggerOutput.tsx, src/Shared/Components/CICDHistory/types.tsx
fix: show reports in  artifact tab in ci and cd when artifact is uploaded but artifact id is not present
=> fix: show reports in artifact tab in ci and cd if artifact is uploaded

package-lock.json, package.json, src/Shared/Components/CollapsibleList/CollapsibleList.component.tsx
=> fix: CollapsibleList - expand icon rotation fix

src/Shared/Components/CICDHistory/LogsRenderer.tsx
=> feat: make search case-insensitive

src/Shared/Components/CICDHistory/LogsRenderer.tsx, src/Shared/Components/CICDHistory/types.tsx
=> feat: incremental log search on individual matches

package-lock.json, package.json, src/Common/RJSF/utils.tsx, src/Shared/Services/ToastManager/toastManager.scss
=> chore: V19-sync-to-v20

package-lock.json, package.json, src/Shared/Components/DatePicker/DateTimePicker.tsx, src/Shared/Components/SelectPicker/utils.ts
1. Window Scroll issue
2. Date picker select hidden issue
=> fix: misc issues

package-lock.json, package.json, src/Shared/Components/DatePicker/TimeSelect.tsx
Deployment window select picker
=> fix: Deployment window select picker

src/Assets/Icon/ic-warning-y5.svg, src/Common/CodeEditor/CodeEditor.tsx, src/Common/CodeEditor/codeEditor.scss, src/Pages/Applications/DevtronApps/Details/AppConfigurations/DeploymentTemplate/DTApplicationMetricsFormField.tsx, src/Pages/Applications/DevtronApps/Details/AppConfigurations/types.ts, src/Shared/Components/InfoIconTippy/InfoIconTippy.tsx, src/Shared/Components/SelectPicker/common.tsx, src/Shared/Components/SelectPicker/constants.ts, src/Shared/Components/SelectPicker/type.ts, src/Shared/Components/SelectPicker/utils.ts, src/Shared/Helpers.tsx
This PR includes:
- SelectPicker small variant
- fixing gaps in App Metrics
- add variant in popup menu type for AppConfig
=> UAT: Deployment template

package-lock.json, package.json, src/Common/ChartVersionAndTypeSelector.tsx
=> fix: chart select

src/Common/ChartVersionAndTypeSelector.tsx
=> fix: code refactoring

package-lock.json, package.json, src/Common/ChartVersionAndTypeSelector.tsx
=> fix: Hotfix v0.20.0

src/index.ts
=> feat: config drift flag

package-lock.json, package.json, src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/DeploymentHistoryConfigDiff.tsx, src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/DeploymentHistoryConfigDiffCompare.tsx, src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/DeploymentHistoryDiffView.tsx, src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/helpers.tsx, src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/types.ts, src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/utils.ts, src/Shared/Components/CICDHistory/TriggerOutput.tsx, src/Shared/Components/CICDHistory/cicdHistory.scss, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.component.tsx, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.types.ts, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.utils.tsx
=> fix: Release App Configurations Bug Fixes

package-lock.json, package.json
=> chore: version bump to 0.6.0

package-lock.json, package.json, src/Common/Hooks/useUrlFilters/types.ts, src/Common/Hooks/useUrlFilters/useUrlFilters.ts, src/Common/Hooks/useUrlFilters/utils.tsx, src/Shared/Components/CICDHistory/History.components.tsx, src/Shared/Components/SelectPicker/FilterSelectPicker.tsx, src/Shared/Components/SelectPicker/type.ts
=> chore: sync persist filters

package-lock.json, package.json, src/Common/CodeEditor/codeEditor.scss, src/Common/Constants.ts, src/Common/RJSF/Form.tsx, src/Pages/ResourceBrowser/ResourceBrowser.Types.ts, src/Pages/ResourceBrowser/index.ts, src/Pages/ResourceBrowser/service.ts
This PR includes changes to add helpers to show gui mode in edit manifest view
=> feat: kubecon manifest gui

package-lock.json, package.json, src/Common/Helper.tsx
=> feat: lock config for k8s manifest (KubeCon 2024)

package-lock.json, package.json, src/Shared/Components/CollapsibleList/CollapsibleList.component.tsx, src/Shared/Components/CollapsibleList/CollapsibleList.types.ts
=> feat: add silver surfer listing

package-lock.json, package.json, src/Common/DraggableWrapper/DraggableWrapper.tsx, src/Common/DraggableWrapper/types.ts, src/Common/Types.ts
add support for screen bottom right in draggable wrapper
=> feat: add support for screen bottom right in draggable wrapper

package-lock.json, package.json, src/Shared/types.ts
=> feat: add support for tippy config in dynamic tab typpe

package-lock.json, package.json, src/Common/Api.ts, src/Common/CodeEditor/codeEditor.scss, src/Common/Constants.ts, src/Common/DraggableWrapper/DraggableWrapper.tsx, src/Common/DraggableWrapper/types.ts, src/Common/Helper.tsx, src/Common/RJSF/Form.tsx, src/Common/Types.ts, src/Pages/ResourceBrowser/ResourceBrowser.Types.ts, src/Pages/ResourceBrowser/index.ts, src/Pages/ResourceBrowser/service.ts, src/Pages/ResourceBrowser/types.ts, src/Shared/API/APIQueuing.ts, src/Shared/Components/BulkSelection/BulkSelectionProvider.tsx, src/Shared/Components/BulkSelection/types.tsx, src/Shared/Components/CollapsibleList/CollapsibleList.component.tsx, src/Shared/Components/CollapsibleList/CollapsibleList.types.ts, src/Shared/Components/Security/SecurityModal/config/ImageScan.tsx, src/Shared/Components/Security/SecurityModal/config/index.ts, src/Shared/Components/Security/SecurityModal/index.ts, src/Shared/types.ts, src/Shared/validations.tsx, src/index.ts
=> feat: kubecon 2024

package-lock.json, package.json, src/Common/SortableTableHeaderCell/SortableTableHeaderCell.tsx
=> fix: full width, height issue for sortable table header cell

package-lock.json, package.json, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.utils.tsx
=> fix: hide config diff for external secret

package-lock.json, package.json, src/Common/Hooks/useUrlFilters/useUrlFilters.ts, src/Common/Policy.Types.ts, src/Shared/Components/Plugin/service.tsx, src/Shared/Components/Plugin/types.ts
=> feat: plugin policy v2

package-lock.json, package.json
=> feat: Webhook UI 1.0.9

package-lock.json, package.json, src/Common/Hooks/useUrlFilters/useUrlFilters.ts
fix: do not set in local storage for undefined
=> fix: do not set in local storage for undefined

package-lock.json, package.json, src/Common/CustomInput/CustomInput.tsx, src/Common/Hooks/useUrlFilters/useUrlFilters.ts
=> fix: on change being called in custom input without any change

package-lock.json, package.json
=> chore: bump version to 1.1.0

package-lock.json, package.json, src/Common/Hooks/useUrlFilters/useUrlFilters.ts
=> fix: updating params twice in local filters

package-lock.json, package.json, src/Common/Hooks/useUrlFilters/useUrlFilters.ts
=> fix: local storage filters updating twice

src/Common/TippyCustomized.tsx
=> fix: remove keydown listener on tippy customized unmount

package-lock.json, package.json, src/Common/Modals/VisibleModal.tsx, src/Shared/Components/CICDHistory/TriggerOutput.tsx, src/Shared/Components/Header/IframePromoButton.tsx
=> fix: set aborting false on abort close

package-lock.json, package.json, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiffMain.tsx
=> fix: diff viewer title issue

src/Common/Markdown/MarkDown.tsx
Add null check in markdown, since if we provide null value then marked method breaks
=> fix: add null check in markdown

src/Shared/Components/DynamicDataTable/DynamicDataTableRow.tsx, src/Shared/Components/DynamicDataTable/types.ts
=> feat: DynamicDataTable - add support to disable delete for individual rows

package-lock.json, package.json, src/Common/Constants.ts, src/Common/Helper.tsx
=> fix: lock config bugs

package-lock.json, package.json, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiffMain.tsx
=> fix: DeploymentConfigDiff - scroll issue, dependency missing fix

package-lock.json, package.json
=> chore: add override for nanoid 3.3.8

package-lock.json, package.json, src/Pages/ResourceBrowser/constants.ts
chore: bump version to 1.2.16 and update ALL_NAMESPACE_OPTION type
=> chore: bump version to 1.2.16 and update ALL_NAMESPACE_OPTION type

package-lock.json, package.json, src/Common/CIPipeline.Types.ts, src/Common/CodeEditor/CodeEditor.reducer.ts, src/Common/CodeEditor/CodeEditor.tsx, src/Common/Common.service.ts, src/Common/Constants.ts, src/Shared/Components/DynamicDataTable/styles.scss
=> fix: CodeEditor value parsing for every mode fix, misc types and scss update, getGlobalVariables service - remove showError

package-lock.json, package.json, src/Shared/Components/SelectPicker/type.ts
=> refactor: SelectPicker - export menuPortalTarget in props

package-lock.json, package.json
=> chore: version bump for common

package-lock.json, package.json, src/Common/Constants.ts
=> fix: pattern start end alphanumeric

src/Common/InfoColorBar/InfoColourbar.tsx, src/Common/Types.ts, src/Pages/GlobalConfigurations/BuildInfra/UseBuildInfraForm.tsx, src/Pages/GlobalConfigurations/BuildInfra/constants.tsx, src/Pages/GlobalConfigurations/BuildInfra/types.tsx, src/Pages/GlobalConfigurations/BuildInfra/utils.tsx
fix: disable fields not supported by buildX in build infra
=> fix: disable fields not supported by buildX in build infra

package-lock.json, package.json, src/Shared/Components/SelectPicker/common.tsx
=> feat: SelectPicker - add tooltip for truncated option

package-lock.json, package.json, src/Common/RJSF/widgets/Checkbox.tsx
fix: improve checkbox selection logic to handle null or undefined values
=> fix: improve checkbox selection logic to handle null or undefined values

package-lock.json, package.json, src/Shared/Components/Security/SecurityModal/SecurityModal.tsx, src/Shared/Components/Security/SecurityModal/constants.tsx, src/Shared/Components/Security/Vulnerabilities/Vulnerabilities.tsx
=> fix: integrate scans

package-lock.json, package.json, src/Shared/Components/DynamicDataTable/DynamicDataTableRow.tsx
=> fix: DynamicDataTable - cellRef check update, rowIds memoised

package-lock.json, package.json, src/Common/Constants.ts, src/Shared/Components/DynamicDataTable/DynamicDataTableRow.tsx, src/Shared/Components/DynamicDataTable/styles.scss, src/Shared/Components/DynamicDataTable/types.ts, src/Shared/Components/SelectPicker/SelectPicker.component.tsx, src/Shared/Components/SelectPicker/SelectPickerTextArea.component.tsx, src/Shared/Components/SelectPicker/common.tsx, src/Shared/Components/SelectPicker/type.ts
=> refactor: dynamic data table

package-lock.json, package.json, src/Shared/Components/SelectPicker/SelectPicker.component.tsx, src/Shared/Components/SelectPicker/common.tsx, src/Shared/Components/SelectPicker/type.ts
=> fix: auto focus issue for select picker

package-lock.json, package.json, src/Common/Common.service.ts
Fixes - https://github.com/devtron-labs/sprint-tasks/issues/1643
=> fix: runtime params env variables

package-lock.json, package.json, src/Common/AppStatus/AppStatus.tsx, src/Pages/GlobalConfigurations/BuildInfra/UseBuildInfraForm.tsx, src/Pages/GlobalConfigurations/BuildInfra/constants.tsx, src/Pages/GlobalConfigurations/BuildInfra/services.tsx, src/Pages/GlobalConfigurations/BuildInfra/types.tsx, src/Pages/GlobalConfigurations/BuildInfra/utils.tsx
=> chore: sync main

package-lock.json, package.json, src/Shared/Components/BulkOperations/BulkOperations.component.tsx
=> chore: change bulk operations success toast text

package-lock.json, package.json, src/Pages/Applications/DevtronApps/Details/CDPipeline/services.ts, src/Pages/Applications/DevtronApps/Details/CDPipeline/types.tsx
=> feat: add isRollbackTrigger to triggerCDNode service

package-lock.json, package.json, src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/DeploymentHistoryConfigDiffCompare.tsx, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.constants.ts
=> feat: DeploymentHistoryConfigDiff - add default sorting - ASC order

package-lock.json, package.json, src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/DeploymentHistoryConfigDiff.tsx, src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/DeploymentHistoryConfigDiffCompare.tsx, src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/DeploymentHistoryDiffView.tsx, src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/types.ts, src/Shared/Components/CICDHistory/types.tsx, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.types.ts, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.utils.tsx, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiffMain.tsx
=> refactor: DeploymentConfigDiff - sorting logic refactor

package-lock.json, package.json, src/Shared/Components/Security/SecurityDetailsCards/SecurityCard.tsx, src/Shared/Components/Security/SecurityDetailsCards/SecurityDetailsCards.tsx, src/Shared/Components/Security/SecurityDetailsCards/types.tsx, src/Shared/Components/Security/Vulnerabilities/Vulnerabilities.tsx, src/Shared/Components/Security/utils.tsx
=> feat: add failed state in scan security card

package-lock.json, package.json, src/Common/RJSF/templates/ObjectFieldTemplate.tsx, src/Common/RJSF/templates/TitleField.tsx
=> feat: add separators between root level entries in RJSF form

package-lock.json, package.json, src/Common/RJSF/templates/ObjectFieldTemplate.tsx, src/Common/RJSF/templates/TitleField.tsx
=> chore: sync rc-27 with main

src/Pages/GlobalConfigurations/BuildInfra/UseBuildInfraForm.tsx, src/Pages/GlobalConfigurations/BuildInfra/utils.tsx
refactor: use structuredClone for deep cloning in BuildInfraForm and utils
QA
=> refactor: use structuredClone for deep cloning in BuildInfraForm and utils

src/Shared/Components/Button/button.scss
=> fix: secondary button bg color

package-lock.json, package.json, src/Common/RJSF/widgets/Select.tsx
=> fix: multi select styling issue

package-lock.json, package.json, src/Assets/Icon/ic-environment.svg, src/Assets/Icon/ic-pulsate-status.svg, src/Common/AppStatus/AppStatus.tsx, src/Common/AppStatus/utils.ts, src/Shared/Components/CICDHistory/Artifacts.tsx, src/Shared/Components/CICDHistory/GitTriggerList.tsx, src/Shared/Components/CICDHistory/Sidebar.tsx, src/Shared/Components/CICDHistory/TriggerDetails.tsx, src/Shared/Components/CICDHistory/constants.tsx, src/Shared/Components/CICDHistory/types.tsx, src/Shared/Components/CICDHistory/utils.tsx, src/Shared/types.ts
feat: add backward compatibility and UAT for Build time breakdown
=> feat: add backward compatibility and UAT for Build time breakdown

package-lock.json, package.json
=> chore: bump version to 1.6.0

package-lock.json, package.json, src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/DeploymentHistoryConfigDiffCompare.tsx
=> fix: DeploymentHistoryConfigDiffCompare - Sort Order resetting on page refresh

package-lock.json, package.json, src/Shared/Components/Textarea/Textarea.component.tsx, src/Shared/Components/Textarea/types.ts
=> fix: text area controlled/uncontrolled issue

package-lock.json, package.json, src/Shared/Components/GettingStartedCard/GettingStarted.tsx, src/Shared/Components/Header/PageHeader.tsx, src/Shared/Components/Header/index.ts, src/Shared/Components/Header/utils.ts
=> fix: posthog-event

package-lock.json, package.json, src/Shared/Components/GettingStartedCard/GettingStarted.tsx, src/Shared/Components/Header/PageHeader.tsx, src/Shared/Components/Header/index.ts, src/Shared/Components/Header/utils.ts
=> chore:  sync main to develop

package-lock.json, package.json, src/Common/CodeEditor/CodeEditor.components.tsx, src/Common/CodeEditor/Extensions/yamlParseLinter.ts, src/Shared/Components/CMCS/ConfigMapSecretReadyOnly.tsx
=> fix: CodeEditor - scss + yamlLint fixes

src/Shared/Components/ModalSidebarPanel/ModalSidebarPanel.component.tsx, src/Shared/Components/ModalSidebarPanel/types.ts, src/Shared/Hooks/useGetResourceKindsOptions/useGetResourceKindsOptions.tsx, src/index.ts
=> feat: create app revamp

src/Pages/Applications/DevtronApps/Details/AppConfigurations/types.ts, src/Shared/validations.tsx
=> feat: GetTemplateAPIRouteType - add route

package-lock.json, package.json, src/Common/RJSF/Form.tsx, src/Shared/validations.tsx
=> fix: use SCHEMA_07_VALIDATOR instead of SCHEMA_07_VALIDATOR_STRICT in rjsf

package-lock.json, package.json, src/Shared/Components/GraphVisualizer/GraphVisualizer.tsx
=> fix: graph visualizer caption

package-lock.json, package.json, src/Shared/Components/CustomInput/CustomInput.tsx
=> fix: remove stop propagation in customInput

package-lock.json, package.json, src/Common/Constants.ts
=> fix: update regex for numbers and add boolean pattern with scope variables

.eslintignore, src/Common/Hooks/UseGetUserRoles/UseGetUserRoles.tsx, src/Common/Hooks/UseGetUserRoles/index.tsx, src/Common/Hooks/UseGetUserRoles/types.ts, src/Common/Hooks/index.ts, src/Shared/Components/CICDHistory/Artifacts.tsx, src/Shared/Components/CICDHistory/History.components.tsx
=> feat: rename superadmin hook

src/Common/EmptyState/GenericEmptyState.tsx, src/Common/Types.ts
=> refactor: remove heightToDeduct from generic empty state

src/Common/Hooks/UseGetUserRoles/UseGetUserRoles.tsx, src/Common/Hooks/UseGetUserRoles/types.ts, src/Shared/Components/ReactSelect/utils.tsx
=> feat: add key hasManagerPermissions in user roles hook

package-lock.json, package.json
chore: update version to 1.8.9-beta-3 in package.json and package-lock
=> chore: update version to 1.8.9-beta-3 in package.json and package-lock

src/Shared/Components/Header/PageHeader.tsx
Includes fix to close theme tippy on click of avatar to open logout card
=> fix: close theme tippy on click of avatar to open logout card

package-lock.json, package.json
=> chore: version bump to 1.9.0

src/Shared/Providers/ThemeProvider/ThemeProvider.tsx, src/Shared/Services/common.service.ts, src/Shared/Services/types.ts
=> feat: add computedAppTheme in user preferences

src/Shared/Components/CICDHistory/StatusFilterButtonComponent.scss, src/Shared/Components/CICDHistory/StatusFilterButtonComponent.tsx
=> fix: StatusFilterButton - ui issue scss fix

package-lock.json, package.json, src/Common/DeleteCINodeButton/DeleteCINodeButton.tsx
=> chore: version bump

package-lock.json, package.json, src/Common/CodeMirror/CodeEditorRenderer.tsx, src/Common/CodeMirror/Extensions/DiffMinimap.tsx
=> fix: CodeEditor - Instance not destroying

package-lock.json, package.json, src/Common/CodeMirror/codeEditor.scss, src/Shared/Components/CICDHistory/CiPipelineSourceConfig.tsx
fix: add error handling and loading state to webhook event fetching
Dev testing
=> chore: add error handling and loading state to webhook event fetching 

package-lock.json, package.json, src/Shared/Components/CountrySelect/CountrySelect.component.tsx, src/Shared/Components/PhoneInput/PhoneInput.component.tsx
chore: update package version to 1.9.8-beta-4 and enhance country select functionality
=> chore: update package version to 1.9.8-beta-4 and enhance country select functionality

package-lock.json, package.json, src/Shared/Components/CICDHistory/TriggerDetails.tsx, src/Shared/Components/CICDHistory/service.tsx
=> feat: add param force abort for pre and post cd

src/Shared/Components/DevtronLicenseCard/DevtronLicenseCard.tsx, src/Shared/Components/DevtronLicenseCard/utils.tsx, src/Shared/Helpers.tsx, src/Shared/constants.tsx
=> feat: add sheen for light and dark mode in license card

package-lock.json, package.json, src/Shared/Components/CICDHistory/TriggerDetails.tsx, src/Shared/Components/CICDHistory/service.tsx
=> chore: sync hotfix 31 for force abort pre-post cd fix

package-lock.json, package.json, src/Shared/Analytics/analytics.ts
=> feat: add prop for prevent redirection on invalid license

package-lock.json, package.json, src/Shared/Components/Button/Button.component.tsx, src/Shared/Components/Button/types.ts
=> feat: add support for anchor tag in Button component

src/Shared/Components/CMCS/validations.ts
=> fix: CM/CS - incorrect validations for required field for yaml fix

package-lock.json, package.json, src/Common/ImageTags.tsx, src/Shared/Components/CICDHistory/Artifacts.tsx, src/Shared/Components/CICDHistory/DeploymentDetailSteps.tsx, src/Shared/Components/CICDHistory/TriggerOutput.tsx
fix: css for release
Dev testing
=> fix: css for release

package-lock.json, package.json, src/Shared/Helpers.tsx, src/Shared/constants.tsx, src/Shared/types.ts
=> feat: remove central api from local storage

package-lock.json, package.json, src/Shared/Components/DevtronLicenseCard/InstallationFingerprintInfo.tsx, src/Shared/Components/Header/HelpNav.tsx, src/Shared/Components/Header/constants.ts, src/Shared/Components/Header/utils.ts
=> feat: add request support link in help nav

package-lock.json, package.json, src/Shared/Components/DevtronLicenseCard/InstallationFingerprintInfo.tsx, src/Shared/Components/Header/HelpNav.tsx, src/Shared/Components/Header/constants.ts, src/Shared/Components/Header/utils.ts
=> chore: sync main trial options

src/Shared/Components/Icon/styles.scss, src/Shared/Components/TabGroup/TabGroup.component.tsx, src/Shared/Components/TabGroup/TabGroup.helpers.tsx, src/Shared/Components/TabGroup/TabGroup.scss, src/Shared/Components/TabGroup/TabGroup.types.ts, src/Shared/Components/TabGroup/TabGroup.utils.ts
=> feat: TabGroup - add support for icon to be rendered via Icon component

src/Shared/Hooks/useForm/useForm.ts
=> feat: useForm - add options in reset, setValue methods

package-lock.json, package.json, src/Common/CodeMirror/CodeEditorRenderer.tsx, src/Common/CodeMirror/Extensions/findAndReplace.tsx, src/Common/CodeMirror/codeEditor.scss, src/Common/CodeMirror/utils.tsx
=> fix: CodeEditor - large file incorrect diff

package-lock.json, package.json
=> chore: update vite to version 5.4.17

package-lock.json, package.json, src/Shared/Components/GitCommitInfoGeneric/GitCommitInfoGeneric.tsx
fix: conditional rendering of generic commit info header
=> fix: conditional rendering of generic commit info header

package-lock.json, package.json, src/Common/EmptyState/emptyState.scss
=> chore: Empty state css for svg dimension

package-lock.json, package.json, src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/DeploymentHistoryConfigDiff.tsx
=> chore: sync develop with main

package-lock.json, package.json, src/index.ts
=> feat: login image cm

package-lock.json, package.json, src/Shared/Components/CodeEditor/codeEditor.scss
=> fix: correct z-index for search panel in code editor

package-lock.json, package.json
=> chore: version bump 1.13.0-pre-9

src/Pages/ResourceBrowser/NodeDrainOptions.tsx
=> fix: set default value for NodeDrainOptions

package-lock.json, package.json, src/Shared/Components/CodeEditor/CodeEditor.tsx
=> chore(version): bump to 1.15.0

package-lock.json, package.json
=> chore(version): bump to 1.16.0

package-lock.json, package.json, src/Common/Hooks/UseRegisterShortcut/types.ts, src/Pages/ResourceBrowser/constants.tsx, src/Shared/Components/CICDHistory/utils.tsx, src/Shared/Components/Table/InternalTable.tsx
=> fix: RB table

package-lock.json, package.json
=> chore: rc 39 version bump

package-lock.json, package.json, src/Shared/Components/DocLink/DocLink.tsx, src/Shared/Components/Header/HelpButton.tsx, src/Shared/Hooks/index.ts, src/Shared/Hooks/useIsSecureConnection/index.ts, src/Shared/Hooks/useIsSecureConnection/useIsSecureConnection.tsx
=> chore: sync main fixes

src/Shared/Components/Error/ErrorBar.tsx, src/Shared/Components/Error/utils.tsx
=> chore: error layout fix

package-lock.json, package.json, src/index.ts
=> feat: sync canary progress

package-lock.json, package.json, src/Shared/Components/Chip/Chip.component.tsx, src/Shared/Components/Chip/types.ts, src/Shared/Components/SelectPicker/common.tsx, src/Shared/Components/SelectPicker/type.ts
=> fix: error in select picker multi value component due to startIcon

package-lock.json, package.json, src/Common/Helper.tsx, src/Shared/Components/ArtifactInfoModal/ArtifactInfoModal.component.tsx, src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiffRadioSelect.tsx, src/Shared/Components/Popover/Popover.component.tsx, src/Shared/Components/Popover/usePopover.hook.ts, src/Shared/Services/app.service.ts
=> refactor: misc fixes

package-lock.json, package.json, src/Common/Modals/VisibleModal.tsx, src/Common/Modals/VisibleModal2.tsx, src/Shared/Components/DTFocusTrap/DTFocusTrap.tsx, src/Shared/Components/DTFocusTrap/index.tsx, src/Shared/Components/DatePicker/DateTimePicker.tsx, src/Shared/Components/Popover/Popover.component.tsx, src/Shared/Components/Popover/usePopover.hook.ts, src/Shared/Components/SelectPicker/utils.ts, src/Shared/Hooks/UseDownload/UseDownload.tsx
=> fix: focus trap misc

src/Shared/Components/Table/InternalTable.tsx, src/Shared/Components/Table/TableContent.tsx, src/Shared/Components/Table/types.ts, src/Shared/Components/Table/utils.ts
=> fix: resource watcher UI

src/Common/Hooks/UseRegisterShortcut/index.ts, src/Shared/Components/ContextSwitcher/ContextSwitcher.tsx, src/Shared/Services/ToastManager/ToastContent.tsx, src/Shared/Services/ToastManager/constants.tsx, src/Shared/Services/ToastManager/toastManager.scss, src/Shared/Services/ToastManager/toastManager.service.tsx, src/Shared/Services/ToastManager/types.ts
=> feat: add shortcut variant to toast manager

package-lock.json, package.json
chore(version): bump version to 1.19.4-pre-5 in package.json and package.json
=> chore(version): bump version to 1.19.4-pre-5 in package.json and package.json

src/Common/SearchBar/SearchBar.component.tsx, src/Common/SearchBar/types.ts, src/Shared/Hooks/useUserPreferences/types.ts, src/index.ts
feat: add loading in search bar and extend user preferences types
=> feat: add loading in search bar and extend user preferences types

package-lock.json, package.json, src/Shared/Hooks/useGetResourceKindsOptions/service.ts, src/Shared/Hooks/useGetResourceKindsOptions/types.ts, src/Shared/Hooks/useGetResourceKindsOptions/useGetResourceKindsOptions.tsx, src/Shared/Hooks/useUserPreferences/types.ts, src/Shared/Services/common.service.ts, src/Shared/Services/types.ts
This pull request refactors how cluster options are fetched and managed in the codebase. The main change is moving the `getClusterOptions` function from the `useGetResourceKindsOptions/service.ts` module to a more general location in `@Shared/Services/common.service.ts`. This improves code organization and reusability. Additionally, related type definitions have been updated to reflect this change, and several unused imports and interfaces have been cleaned up. There are also minor updates to user preference command bar item types.
* Moved the `getClusterOptions` function from `src/Shared/Hooks/useGetResourceKindsOptions/service.ts` to `src/Shared/Services/common.service.ts` for better code reuse and organization. All relevant imports and usages were updated accordingly. …
=> feat: cmd bar resource search

package-lock.json, package.json, src/Common/API/CoreAPI.ts, src/Common/API/index.ts, src/Shared/Components/ConfirmationModal/ForceDeleteConfirmationModal.tsx, src/Shared/Components/ConfirmationModal/types.ts
=> chore: main pull

package-lock.json, package.json, src/Shared/Components/ContextSwitcher/ContextSwitcher.tsx, src/Shared/Components/ContextSwitcher/types.ts
=> feat: resource context added in context switcher
