devtron-labs/devtron-fe-common-lib

package.json
src/Common/CustomTagSelector/TagDetails.tsx
src/Common/CustomTagSelector/TagLabelSelect.tsx
src/Common/CustomTagSelector/TagLabelValueSelector.tsx
src/Common/CustomTagSelector/ValidationRules.ts

Handled the fix in which if the key is "devtron.ai/" the check in both key and value section would be disabled and also the propagate tags would be disabled.

fix: error-handling-in-tags

---

package-lock.json
package.json
src/Common/RadioGroup.tsx
src/Common/Types.ts

This PR contains the changes of radioGroup enhancement which is add disabled option on Radiogroup item
Fixes # [3509](https://github.com/devtron-labs/devtron/issues/3509)
Tested manually with hardcoded data

feat: Radio group enhancement

---

package-lock.json
package.json
src/Common/EmptyState/GenericEmptyState.tsx
src/Common/EmptyState/emptyState.scss
src/Common/Types.ts

Add support for row & column layout in the `GenericEmptyState` component

feat: add support for row layout in generic empty state

---

src/Common/Security/scanVulnerabilities.css

Put an upper limit on the `width` of the cells in the security vulnerability  scans table, to avoid overflowing of text and disturbing the cell alignment like in the below screenshot:
After fix:
https://github.com/devtron-labs/devtron-fe-common-lib/assets/146105157/70d0da7f-00b0-41b7-a7d1-b868bf5e8d54

Fix max-width for scanVulnerabilities Table cells

---

package-lock.json
package.json
src/Common/Constants.ts
src/Shared/Components/CICDHistory/LogsRenderer.tsx
src/Shared/Helpers.tsx

This PR fixes the bug wherein logs renderer we replaced the matched portion of logs with searchText itself instead of match.

fix: revert search working as regex search for logs

---

package-lock.json
package.json
src/Common/CodeEditor/CodeEditor.tsx
src/Common/CodeEditor/types.ts

Dynamically adjust the height of the code editor such that the scroll inside code editor does not appear. This feature can be enabled through the newly added prop `adjustEditorHeightToContent`

feat: add support for content based editor height

---

package-lock.json
package.json
src/Common/Common.service.ts

fix: filter users with no image approver access from user group data store

fix: filter users with no image approver access from user group data store

---

package-lock.json
package.json
src/Shared/Components/Plugin/PluginList.tsx

fix: remove unused error variable from catch

fix: remove unused error variable from catch

---

package-lock.json
package.json
src/Common/ChartVersionAndTypeSelector.tsx
src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/DeploymentHistoryConfigDiff.tsx
src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/DeploymentHistoryConfigDiffCompare.tsx
src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/DeploymentHistoryDiffView.tsx
src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/helpers.tsx
src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/types.ts
src/Shared/Components/CICDHistory/DeploymentHistoryConfigDiff/utils.ts
src/Shared/Components/CICDHistory/TriggerOutput.tsx
src/Shared/Components/CICDHistory/service.tsx
src/Shared/Components/CICDHistory/types.tsx
src/Shared/Components/Collapse/Collapse.tsx
src/Shared/Components/CollapsibleList/CollapsibleList.component.tsx
src/Shared/Components/CollapsibleList/CollapsibleList.types.ts
src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.component.tsx
src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.types.ts
src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.utils.tsx
src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiffAccordion.tsx
src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiffMain.tsx
src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiffNavigation.tsx
src/Shared/Services/app.service.ts
src/Shared/Services/app.types.ts

feat: Pipeline deploy config diff revamp UAT Changes

---

src/Common/Hooks/UseRegisterShortcut/UseRegisterShortcutProvider.tsx

The first a shortcut timesout it works but consecutive timeouts don't happen unless we trigger a keyup.
Just moved the code that registers the timeout to the end of the handle key down event handler.

fix: timeout not registered a second time unless keyup event is fired

---

src/Shared/Components/Button/Button.component.tsx
src/Shared/Components/Button/types.ts
src/Shared/Components/SelectPicker/common.tsx

feat: Button - add support for fullWidth prop, Select Picker - option w-100 style

---

package-lock.json
package.json
src/Shared/types.ts

feat: terminal permission from user permissions

---

package-lock.json
package.json
src/Assets/Icon/ic-file-code.svg
src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.component.tsx
src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.scss
src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.types.ts
src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiff.utils.tsx
src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiffMain.tsx
src/Shared/Components/DeploymentConfigDiff/DeploymentConfigDiffNavigation.tsx

fix: cm secret bug fixes & UAT changes

---

package-lock.json
package.json
src/Assets/Icon/ic-caret-down-small.svg
src/Common/RJSF/templates/FieldErrorTemplate.tsx
src/Common/RJSF/templates/ObjectFieldTemplate.tsx
src/Shared/Components/Header/HeaderWithCreateButton/HeaderWithCreateButon.tsx
src/Shared/Components/Header/HeaderWithCreateButton/HeaderWithCreateButton.scss
src/Shared/Components/Header/IframePromoButton.tsx
src/Shared/Components/Header/PageHeader.tsx
src/index.ts

chore: sync main dt21

---

package-lock.json
package.json
src/Shared/Hooks/useGetResourceKindsOptions/service.ts
src/Shared/Hooks/useGetResourceKindsOptions/types.ts
src/Shared/Hooks/useGetResourceKindsOptions/useGetResourceKindsOptions.tsx

fix: group env options by cluster

---

package-lock.json
package.json
src/index.ts

feat: add feature flag for hiding direct permissions in User permissions

feat: add feature flag for hiding direct permissions in User permissions

---

package-lock.json
package.json
src/Common/Constants.ts
src/Common/Helper.tsx
src/Shared/types.ts
src/Shared/validations.tsx

This PR includes changes:
- to support monitoring tab in resource browser.
- helpers like validateIframeString, getSanitizedIframe and getIframeWithDefaultAttributes.
- types for dom purify

feat: rb monitoring

---

package-lock.json
package.json
src/Common/Api.ts
src/Common/Types.ts
src/Shared/types.ts

refactor: resource browser tabs clean up and add abortControllerRef in fetchInTime

---

package-lock.json
package.json
src/Common/AppStatus/AppStatus.tsx
src/Pages/GlobalConfigurations/BuildInfra/UseBuildInfraForm.tsx
src/Pages/GlobalConfigurations/BuildInfra/constants.tsx
src/Pages/GlobalConfigurations/BuildInfra/services.tsx
src/Pages/GlobalConfigurations/BuildInfra/types.tsx
src/Pages/GlobalConfigurations/BuildInfra/utils.tsx

This PR includes changes to inculcate useBuildXDriver flag at profile level.

feat: add useBuildXDriver in build infra

---

src/Shared/Components/CICDHistory/LogsRenderer.scss
src/Shared/Components/CICDHistory/TriggerDetails.tsx

fix: logs renderer line number to accomodate till 99999 in single line and add padding for build in progress
Dev test

fix: logs renderer line number to accomodate till 99999 in single line and add padding for build in progress.

---

package-lock.json
package.json

chore: bump version to 1.12.0-pre-8 in package.json and package-lock.json

chore: bump version to 1.12.0-pre-8 in package.json and package-lock.json

---

package-lock.json
package.json
src/Shared/Components/TabGroup/TabGroup.component.tsx
src/Shared/Components/TabGroup/TabGroup.helpers.tsx

fix: tab group animation

---

src/Assets/IconV2/ic-arrows-clockwise.svg
src/Assets/IconV2/ic-filter-applied.svg
src/Assets/IconV2/ic-filter.svg
src/Assets/IconV2/ic-hibernate-circle.svg
src/Assets/IconV2/ic-hibernate.svg
src/Assets/IconV2/ic-more-vertical.svg
src/Assets/IconV2/ic-sun.svg
src/Assets/IconV2/ic-traffic-signal.svg
src/Common/Checkbox.tsx
src/Common/Types.ts
src/Shared/Components/Icon/Icon.tsx
src/Shared/Components/StatusComponent/utils.ts

feat: Checkbox - add error prop, add new icons

---

package-lock.json
package.json

chore(version): bump version to 1.17.0-pre-5 in package.json and package-lock.json

chore(version): bump version to 1.17.0-pre-5 in package.json and package-lock.json

---

package-lock.json
package.json
src/Shared/Components/DocLink/DocLink.tsx
src/Shared/Components/Header/HelpButton.tsx
src/Shared/Hooks/index.ts
src/Shared/Hooks/useIsSecureConnection/index.ts
src/Shared/Hooks/useIsSecureConnection/useIsSecureConnection.tsx

feat: implement useIsSecureConnection hook and integrate it into DocLink and HelpButton components

---

package-lock.json
package.json
src/Common/API/CoreAPI.ts
src/Common/API/index.ts
src/Shared/Components/ConfirmationModal/ForceDeleteConfirmationModal.tsx
src/Shared/Components/ConfirmationModal/types.ts

This pull request introduces a new API timeout configuration feature and improves the force delete confirmation modal by adding a loading state to the delete button. The most important changes are grouped below by theme.
**API Timeout Configuration:**
* Added a `setGlobalAPITimeout` method to the `CoreAPI` class, allowing global adjustment of the API request timeout.
* Exported `setGlobalAPITimeout` from the API module for use throughout the application.
**Force Delete Confirmation Modal Improvements:**
* Updated `ForceDeleteConfirmationProps` to include an optional `isDeleting` property, enabling loading state management for the modal.
* Passed the `isDeleting` prop to the modal component and the primary button, displaying a loading indicator during deletion. …

feat: add global API timeout setting and enhance force delete confirmation modal

---

package-lock.json
package.json
src/Common/Common.service.ts
src/Common/Types.ts
src/Pages-Devtron-2.0/CostVisibility/Shared/constants.tsx
src/Pages-Devtron-2.0/CostVisibility/Shared/index.ts
src/Pages-Devtron-2.0/CostVisibility/Shared/types.ts
src/Shared/Components/PrometheusConfigurations/PrometheusConfigCard.tsx
src/Shared/Components/PrometheusConfigurations/types.ts

This pull request introduces enhancements and refactoring to the cost visibility and cluster management features, focusing on improved type safety, extensibility, and clarity in data handling. The main changes include new type definitions for cluster cost module configuration, updates to how cluster details are constructed and returned, and the addition of shared constants and types for cost visibility. Minor cleanups and formatting improvements are also included.
* Added new types to describe cluster cost module configuration and installation status, including error handling, in `src/Common/Types.ts`. The `ClusterDetailDTO` interface now includes a `costModuleConfig` property for richer cost module metadata. [[1]](diffhunk://#diff-a9ac7aca6644994fc547ab75e72a243eedcb8e1f8f27d947836cfd40af …

feat: cost config

---

package-lock.json
package.json
src/Common/API/CoreAPI.ts
src/Common/API/types.ts

This pull request introduces a new feature to the API request logic, allowing requests to be routed through a proxy host when needed. The main change is the addition of an `isProxyHost` parameter to the API functions, which modifies the request URL accordingly. This update is reflected in both the API interface and implementation.
**API enhancements:**
* Added an `isProxyHost` boolean parameter to the `FetchAPIParamsType` interface in `src/Common/API/types.ts`, allowing requests to specify if they should use the proxy host.
* Updated the `CoreAPI.fetch` method in `src/Common/API/CoreAPI.ts` to accept the new `isProxyHost` parameter and adjust the request URL to use `/proxy` when set to true. [[1]](diffhunk://#diff-4567818b64e97e6cc17a681b9b6d47b1b3fbf5e2b77dfeeb99a7c553d20f2759R52) …

feat: proxy host

---

package-lock.json
package.json
src/Common/API/CoreAPI.ts
src/Common/API/types.ts
src/Common/Types.ts

fix: update version to 1.20.5-pre-6 and add isProxyHost option to API interfaces

fix: update version to 1.20.5-pre-6 and add isProxyHost option to API interfaces
